//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingHelperFilesCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildingHelperFilesCreator.Resources.ru", typeof(ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 801; 166.
        /// </summary>
        internal static string BuildingHelperForm_Size {
            get {
                return ResourceManager.GetString("BuildingHelperForm.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0; 127.
        /// </summary>
        internal static string Control_BotPannel_Location {
            get {
                return ResourceManager.GetString("Control.BotPannel.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 595; 71.
        /// </summary>
        internal static string Control_CreateFilesButton_Location {
            get {
                return ResourceManager.GetString("Control.CreateFilesButton.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 188; 21.
        /// </summary>
        internal static string Control_CreateFilesButton_Size {
            get {
                return ResourceManager.GetString("Control.CreateFilesButton.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить скрипты.
        /// </summary>
        internal static string Control_CreateFilesButton_Text {
            get {
                return ResourceManager.GetString("Control.CreateFilesButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12; 17.
        /// </summary>
        internal static string Control_CurrentDirrectoryLabel_Location {
            get {
                return ResourceManager.GetString("Control.CurrentDirrectoryLabel.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая папка.
        /// </summary>
        internal static string Control_CurrentDirrectoryLabel_Text {
            get {
                return ResourceManager.GetString("Control.CurrentDirrectoryLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153; 17.
        /// </summary>
        internal static string Control_CurrentDirrectoryTextBox_Location {
            get {
                return ResourceManager.GetString("Control.CurrentDirrectoryTextBox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 629; 20.
        /// </summary>
        internal static string Control_CurrentDirrectoryTextBox_Size {
            get {
                return ResourceManager.GetString("Control.CurrentDirrectoryTextBox.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 595; 47.
        /// </summary>
        internal static string Control_CustomStrategiesCheckBox_Location {
            get {
                return ResourceManager.GetString("Control.CustomStrategiesCheckBox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 185; 17.
        /// </summary>
        internal static string Control_CustomStrategiesCheckBox_Size {
            get {
                return ResourceManager.GetString("Control.CustomStrategiesCheckBox.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разные стратегии для локаций.
        /// </summary>
        internal static string Control_CustomStrategiesCheckBox_Text {
            get {
                return ResourceManager.GetString("Control.CustomStrategiesCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153; 71.
        /// </summary>
        internal static string Control_DefaultStrategyComboBox_Location {
            get {
                return ResourceManager.GetString("Control.DefaultStrategyComboBox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192; 21.
        /// </summary>
        internal static string Control_DefaultStrategyComboBox_Size {
            get {
                return ResourceManager.GetString("Control.DefaultStrategyComboBox.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12; 74.
        /// </summary>
        internal static string Control_DefaultStrategyLabel_Location {
            get {
                return ResourceManager.GetString("Control.DefaultStrategyLabel.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 133; 13.
        /// </summary>
        internal static string Control_DefaultStrategyLabel_Size {
            get {
                return ResourceManager.GetString("Control.DefaultStrategyLabel.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стратегия по умолчанию.
        /// </summary>
        internal static string Control_DefaultStrategyLabel_Text {
            get {
                return ResourceManager.GetString("Control.DefaultStrategyLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Control_ExitToolStrip_Text {
            get {
                return ResourceManager.GetString("Control.ExitToolStrip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string Control_HelpToolStrip_Text {
            get {
                return ResourceManager.GetString("Control.HelpToolStrip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Control_LanguageToolStrip_Text {
            get {
                return ResourceManager.GetString("Control.LanguageToolStrip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12; 48.
        /// </summary>
        internal static string Control_MapNameLabel_Location {
            get {
                return ResourceManager.GetString("Control.MapNameLabel.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя карты.
        /// </summary>
        internal static string Control_MapNameLabel_Text {
            get {
                return ResourceManager.GetString("Control.MapNameLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 153; 45.
        /// </summary>
        internal static string Control_MapNameTextBox_Location {
            get {
                return ResourceManager.GetString("Control.MapNameTextBox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192; 20.
        /// </summary>
        internal static string Control_MapNameTextBox_Size {
            get {
                return ResourceManager.GetString("Control.MapNameTextBox.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть карту.
        /// </summary>
        internal static string Control_OpenMapFolderMenuItem_Text {
            get {
                return ResourceManager.GetString("Control.OpenMapFolderMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 489; 45.
        /// </summary>
        internal static string Control_PeaceTimeComboBox_Location {
            get {
                return ResourceManager.GetString("Control.PeaceTimeComboBox.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 368; 48.
        /// </summary>
        internal static string Control_PeaceTimeLabel_Location {
            get {
                return ResourceManager.GetString("Control.PeaceTimeLabel.Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99; 13.
        /// </summary>
        internal static string Control_PeaceTimeLabel_Size {
            get {
                return ResourceManager.GetString("Control.PeaceTimeLabel.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время перемирия.
        /// </summary>
        internal static string Control_PeaceTimeLabel_Text {
            get {
                return ResourceManager.GetString("Control.PeaceTimeLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 785; 105.
        /// </summary>
        internal static string Control_TopPannel_Size {
            get {
                return ResourceManager.GetString("Control.TopPannel.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немецкий.
        /// </summary>
        internal static string Language_de {
            get {
                return ResourceManager.GetString("Language.de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string Language_en {
            get {
                return ResourceManager.GetString("Language.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Польский.
        /// </summary>
        internal static string Language_pl {
            get {
                return ResourceManager.GetString("Language.pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Language_ru {
            get {
                return ResourceManager.GetString("Language.ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локация.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандарт.
        /// </summary>
        internal static string Strategy_BS_Default_60 {
            get {
                return ResourceManager.GetString("Strategy.BS_Default_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 конюшни.
        /// </summary>
        internal static string Strategy_BS_DoubleStable_60 {
            get {
                return ResourceManager.GetString("Strategy.BS_DoubleStable_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только железо.
        /// </summary>
        internal static string Strategy_BS_IronOnly_60 {
            get {
                return ResourceManager.GetString("Strategy.BS_IronOnly_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только железо(на одну атаку).
        /// </summary>
        internal static string Strategy_BS_IronRush_60 {
            get {
                return ResourceManager.GetString("Strategy.BS_IronRush_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3+2.
        /// </summary>
        internal static string Strategy_BS_IronStoring_60 {
            get {
                return ResourceManager.GetString("Strategy.BS_IronStoring_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только кожа.
        /// </summary>
        internal static string Strategy_BS_LeatherOnly_60 {
            get {
                return ResourceManager.GetString("Strategy.BS_LeatherOnly_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string Strategy_BS_Null {
            get {
                return ResourceManager.GetString("Strategy.BS_Null", resourceCulture);
            }
        }
    }
}
